version: "3"
services:
  application:
    image: ruby4eyes/spring-boot-mysql-app
    ports:
      - "8080:8080"
    networks:
      - springboot-mysqldb-net
    depends_on:
      - mysqldb
    
  mysqldb:
    image: mysql:5.7
    networks:
      - springboot-mysqldb-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbms
    
networks:
  springboot-mysqldb-net:
